home:
  path: /
  permission: 'access'

login:
  path: /user/login
  permission: 'access'

admin:
  path: /admin
  permission: 'administrator'

error404:
  path: /404
  permission: 'access'

error403:
  path: /403
  permission: 'access'
